export enum EtatBonPour {

  INITIAL = 'INITIAL',
  ALLERDLF = 'TRANSMIS AU DLF',
  ALLERBLM = 'TRANSMIS AU BLM',
  ALLERSECTION = 'TRANSMIS A LA SECTION',
  RETOURSECTION = 'RETRANSMIS A LA SECTION',
  RETOURBLM = 'RETRANSMIS AU BLM',
  RETOURDLF = 'RETRANSMIS AU DLF'
  
  
}
