export enum EtatBonPour {

  INITIAL = 'INITIAL',
  ALLERDLF = 'TRANSMIS AU DLF',
  ALLERBLM = 'TRANSMIS AU BLM',
  ALLERSECTION = 'TRANSMIS AU SECTION',
  RETOURDLF = 'RETRANSMIS AU DLF',
  RETOURBLM = 'RETRANSMIS AU BLM',
  RETOURSECTION = 'RETRANSMIS AU SECTION',
}
